# Generated by Django 3.0 on 2026-05-18 13:48

from django.db import migrations


def copy_profile(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')

    for obj in OldProfile.objects.all():
        NewProfile.objects.create(
            id=obj.id,
            user=obj.user,
            favorite_city=obj.favorite_city,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_profile),
    ]
