# Generated by Django 3.0 on 2026-05-18 13:43

from django.db import migrations


def copy_address(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    NewAddress = apps.get_model('lettings', 'Address')

    for obj in OldAddress.objects.all():
        NewAddress.objects.create(
            id=obj.id,
            number=obj.number,
            street=obj.street,
            city=obj.city,
            state=obj.state,
            zip_code=obj.zip_code,
            country_iso_code=obj.country_iso_code,
        )


def copy_lettings(apps, schema_editor):
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('lettings', 'Letting')
    NewAddress = apps.get_model('lettings', 'Address')

    for obj in OldLetting.objects.all():

        new_address = NewAddress.objects.get(id=obj.address.id)

        NewLetting.objects.create(
            id=obj.id,
            title=obj.title,
            address=new_address,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_address),
        migrations.RunPython(copy_lettings),
    ]
